version: '3.7'

services:
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
        SA_PASSWORD: "StrongP@ssw0rd123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports:
        - "1450:1433" 
    volumes:
      - sqlserverdata:/var/opt/mssql

  newsletterapi:
    image: ${DOCKER_REGISTRY-}newsletterapi
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5038:80"

volumes:
    sqlserverdata: